services:
  web:
    build:
      context: ./apache
    depends_on:
      - db
    ports:
      - "8080:80"
    configs:
      - source: apache_conf
        target: /usr/local/apache2/conf/httpd.conf
    volumes:
      - ./www:/usr/local/apache2/htdocs:ro
      - ./cgi-bin:/usr/local/apache2/cgi-bin:ro
    secrets:
      - api_key
      - pg_pass
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ejemplo
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pass
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
    secrets:
      - pg_pass

configs:
  apache_conf:
    file: ./apache/httpd.conf

secrets:
  api_key:
    file: ./secrets/API_KEY.txt
  pg_pass:
    file: ./secrets/POSTGRES_PASSWORD.txt
